apiVersion: apps/v1
kind: Deployment
metadata:
  name: louden-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: louden-springboot
  template:
    metadata:
      labels:
        app: louden-springboot
    spec:
      containers:
        - name: springboot
          image: louden/louden-docker-demo:louden-docker-demo
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
---
apiVersion: v1
kind: Service
metadata:
  name: louden-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 7000
  selector:
    app: louden-springboot
